#!/bin/bash
echo "=== T con: Breakdown of remaining 1828 lines ==="
echo ""
echo "t_prog_compiler.c (707 lines):"
echo "  - compile_program: core, must stay"
echo "  - compile_func: core, must stay"  
echo "  - compile_f_block: core, must stay"
echo "  - compile_line: core, must stay"
echo "  - run_file: core, must stay"
echo "  → ~707 lines unavoidable (compiler logic)"
echo ""
echo "t_bytecode.h (438 lines):"
echo "  - VM dispatch loop: must stay"
echo "  - OP handlers: must stay"
echo "  - Frame management: must stay"
echo "  → ~438 lines unavoidable (VM)"
echo ""
echo "t_natives.h (660 lines):"
grep -c "^double nat_\|^char\* nat_\|^void nat_" src/t_natives.h | xargs echo "  - Function implementations:"
grep -c "REG1\|REG_S1\|REG_S2\|func_count++" src/t_natives.h | xargs echo "  - Registration lines:"
echo "  → Target: ~300 lines (remove more logic natives)"
echo ""
echo "t_signal.h (23 lines): minimal, keep"
echo ""
echo "Real minimum: ~1500 lines"
echo "Current: 1828 lines"
echo "Reducible: ~328 more lines"
